jenkins:
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  numExecutors: 2
  scmCheckoutRetryCount: 0
  mode: NORMAL

credentials:
  system:
    domainCredentials:
    - domain: {}
      credentials:
      - string:
          scope: GLOBAL
          id: "sonar-token"
          secret: "${readFile:/run/secrets/sonar-token}"
          description: "SonarQube token"

unclassified:
  location:
    url: "http://localhost:8085/"
  # Configuration to get Jenkins metrics into Prometheus so that 
  # the Grafana dashboard has data to diplay
  prometheusConfiguration:
    path: "prometheus"
    defaultNamespace: "default"
    jobAttributeName: "jenkins_job"
    useAuthenticatedEndpoint: false
    collectingMetricsPeriodInSeconds: 120
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countAbortedBuilds: true
    fetchTestResults: true
    processingDisabledBuilds: false
    appendParamLabel: false
    appendStatusLabel: false
    perBuildMetrics: false
    collectDiskUsage: false
    collectNodeStatus: true
    collectCodeCoverage: false
  sonarGlobalConfiguration:
    buildWrapperEnabled: false
    installations:
    - name: "sonarqube"
      serverUrl: "${SONAR_HOST_URL}"
      serverAuthenticationToken: "sonar-token"
  scmGit:
    addGitTagAction: false
    createAccountBasedOnEmail: false
  gitHubPluginConfig:
    hookUrl: "http://localhost:8085/github-webhook/"

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "M3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.9.14"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"

jobs:
  - script: |
      def jenkinsfileContent = new File('/var/jenkins_home/Jenkinsfile').text
      pipelineJob('spring-petclinic') {
        definition {
          cps {
            script(jenkinsfileContent)
            sandbox(true)
          }
        }
      }
